
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForHttp4sCore extends BleepCodegenScript("GenerateForHttp4sCore") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("http4s-core@js213", "http4s-core@jvm213").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package org.http4s
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "1.0-bc06627-20230529T103202Z-SNAPSHOT". */
      |  val version: String = "1.0-bc06627-20230529T103202Z-SNAPSHOT"
      |  /** The value is "2.13.8". */
      |  val scalaVersion: String = "2.13.8"
      |  /** The value is (1 -> 0). */
      |  val apiVersion = (1 -> 0)
      |  override val toString: String = {
      |    "version: %s, scalaVersion: %s, apiVersion: %s".format(
      |      version, scalaVersion, apiVersion
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set("http4s-core@js3", "http4s-core@jvm3").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package org.http4s
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "1.0-bc06627-20230529T103331Z-SNAPSHOT". */
      |  val version: String = "1.0-bc06627-20230529T103331Z-SNAPSHOT"
      |  /** The value is "3.1.1". */
      |  val scalaVersion: String = "3.1.1"
      |  /** The value is (1 -> 0). */
      |  val apiVersion = (1 -> 0)
      |  override val toString: String = {
      |    "version: %s, scalaVersion: %s, apiVersion: %s".format(
      |      version, scalaVersion, apiVersion
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}