// $COVERAGE-OFF$
package zio.concurrent

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "dev.zio". */
  final val organization = "dev.zio"
  /** The value is "zio-concurrent". */
  final val moduleName = "zio-concurrent"
  /** The value is "zio-concurrent". */
  final val name = "zio-concurrent"
  /** The value is "2.1.26+231-18e9a918-SNAPSHOT". */
  final val version = "2.1.26+231-18e9a918-SNAPSHOT"
  /** The value is "2.12.21". */
  final val scalaVersion = "2.12.21"
  /** The value is "1.13.0". */
  final val sbtVersion = "1.13.0"
  /** The value is true. */
  final val isSnapshot = true
  /** The value is false. */
  final val optimizationsEnabled = false
  override val toString: String = {
    import _root_.scala.StringContext
    s"organization: ${organization}, moduleName: ${moduleName}, name: ${name}, version: ${version}, scalaVersion: ${scalaVersion}, sbtVersion: ${sbtVersion}, isSnapshot: ${isSnapshot}, optimizationsEnabled: ${optimizationsEnabled}"
  }
}
// $COVERAGE-ON$
