// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scala.meta.internal.semanticdb

@SerialVersionUID(0L)
final case class Scope(
    symlinks: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    hardlinks: _root_.scala.Seq[scala.meta.internal.semanticdb.SymbolInformation] = _root_.scala.Seq.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Scope] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      symlinks.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      }
      hardlinks.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      symlinks.foreach { __v =>
        val __m = __v
        _output__.writeString(1, __m)
      };
      hardlinks.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
    }
    def clearSymlinks = copy(symlinks = _root_.scala.Seq.empty)
    def addSymlinks(__vs: _root_.scala.Predef.String *): Scope = addAllSymlinks(__vs)
    def addAllSymlinks(__vs: Iterable[_root_.scala.Predef.String]): Scope = copy(symlinks = symlinks ++ __vs)
    def withSymlinks(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Scope = copy(symlinks = __v)
    def clearHardlinks = copy(hardlinks = _root_.scala.Seq.empty)
    def addHardlinks(__vs: scala.meta.internal.semanticdb.SymbolInformation *): Scope = addAllHardlinks(__vs)
    def addAllHardlinks(__vs: Iterable[scala.meta.internal.semanticdb.SymbolInformation]): Scope = copy(hardlinks = hardlinks ++ __vs)
    def withHardlinks(__v: _root_.scala.Seq[scala.meta.internal.semanticdb.SymbolInformation]): Scope = copy(hardlinks = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => symlinks
        case 2 => hardlinks
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(symlinks.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 2 => _root_.scalapb.descriptors.PRepeated(hardlinks.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: scala.meta.internal.semanticdb.Scope.type = scala.meta.internal.semanticdb.Scope
    // @@protoc_insertion_point(GeneratedMessage[scala.meta.internal.semanticdb.Scope])
}

object Scope extends scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb.Scope] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb.Scope] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): scala.meta.internal.semanticdb.Scope = {
    val __symlinks: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    val __hardlinks: _root_.scala.collection.immutable.VectorBuilder[scala.meta.internal.semanticdb.SymbolInformation] = new _root_.scala.collection.immutable.VectorBuilder[scala.meta.internal.semanticdb.SymbolInformation]
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __symlinks += _input__.readStringRequireUtf8()
        case 18 =>
          __hardlinks += _root_.scalapb.LiteParser.readMessage[scala.meta.internal.semanticdb.SymbolInformation](_input__)
        case tag => _input__.skipField(tag)
      }
    }
    scala.meta.internal.semanticdb.Scope(
        symlinks = __symlinks.result(),
        hardlinks = __hardlinks.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[scala.meta.internal.semanticdb.Scope] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      scala.meta.internal.semanticdb.Scope(
        symlinks = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        hardlinks = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[scala.meta.internal.semanticdb.SymbolInformation]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SemanticdbProto.javaDescriptor.getMessageTypes().get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SemanticdbProto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = scala.meta.internal.semanticdb.SymbolInformation
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = scala.meta.internal.semanticdb.Scope(
    symlinks = _root_.scala.Seq.empty,
    hardlinks = _root_.scala.Seq.empty
  )
  implicit class ScopeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb.Scope]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, scala.meta.internal.semanticdb.Scope](_l) {
    def symlinks: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.symlinks)((c_, f_) => c_.copy(symlinks = f_))
    def hardlinks: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[scala.meta.internal.semanticdb.SymbolInformation]] = field(_.hardlinks)((c_, f_) => c_.copy(hardlinks = f_))
  }
  final val SYMLINKS_FIELD_NUMBER = 1
  final val HARDLINKS_FIELD_NUMBER = 2
  def of(
    symlinks: _root_.scala.Seq[_root_.scala.Predef.String],
    hardlinks: _root_.scala.Seq[scala.meta.internal.semanticdb.SymbolInformation]
  ): _root_.scala.meta.internal.semanticdb.Scope = _root_.scala.meta.internal.semanticdb.Scope(
    symlinks,
    hardlinks
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[scala.meta.internal.semanticdb.Scope])
}
