// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scala.meta.internal.semanticidx

object SemanticidxProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      scala.meta.internal.semanticidx.Indexes,
      scala.meta.internal.semanticidx.Index,
      scala.meta.internal.semanticidx.EntryMessage,
      scala.meta.internal.semanticidx.PackageEntry,
      scala.meta.internal.semanticidx.ToplevelEntry
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChFzZW1hbnRpY2lkeC5wcm90bxIfc2NhbGEubWV0YS5pbnRlcm5hbC5zZW1hbnRpY2lkeBoVc2NhbGFwYi9zY2FsYXBiLnByb
  3RvIlkKB0luZGV4ZXMSTgoHaW5kZXhlcxgBIAMoCzImLnNjYWxhLm1ldGEuaW50ZXJuYWwuc2VtYW50aWNpZHguSW5kZXhCDOI/C
  RIHaW5kZXhlc1IHaW5kZXhlcyLeAQoFSW5kZXgSWwoHZW50cmllcxgBIAMoCzIzLnNjYWxhLm1ldGEuaW50ZXJuYWwuc2VtYW50a
  WNpZHguSW5kZXguRW50cmllc0VudHJ5QgziPwkSB2VudHJpZXNSB2VudHJpZXMaeAoMRW50cmllc0VudHJ5EhoKA2tleRgBIAEoC
  UII4j8FEgNrZXlSA2tleRJICgV2YWx1ZRgCIAEoCzImLnNjYWxhLm1ldGEuaW50ZXJuYWwuc2VtYW50aWNpZHguRW50cnlCCuI/B
  xIFdmFsdWVSBXZhbHVlOgI4ASLrAQoFRW50cnkSZgoMcGFja2FnZUVudHJ5GAEgASgLMi0uc2NhbGEubWV0YS5pbnRlcm5hbC5zZ
  W1hbnRpY2lkeC5QYWNrYWdlRW50cnlCEeI/DhIMcGFja2FnZUVudHJ5SABSDHBhY2thZ2VFbnRyeRJqCg10b3BsZXZlbEVudHJ5G
  AIgASgLMi4uc2NhbGEubWV0YS5pbnRlcm5hbC5zZW1hbnRpY2lkeC5Ub3BsZXZlbEVudHJ5QhLiPw8SDXRvcGxldmVsRW50cnlIA
  FINdG9wbGV2ZWxFbnRyeUIOCgxzZWFsZWRfdmFsdWUiDgoMUGFja2FnZUVudHJ5IisKDVRvcGxldmVsRW50cnkSGgoDdXJpGAEgA
  SgJQgjiPwUSA3VyaVIDdXJpQgXiPwJIAGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}