package bleep

import bleep.bsp.{BspServerClasspathSource, InProcessBspServer}
import bleep.commands.BuildCreateNew
import bleep.internal.{bleepLoggers, FileUtils}
import org.scalatest.Assertion
import org.scalatest.funsuite.AnyFunSuite
import ryddig.*

import java.nio.file.{Files, Path}
import java.time.Instant
import scala.collection.mutable
import scala.concurrent.{ExecutionContext, ExecutionContextExecutor}

/** Base for integration tests.
  *
  * Each test:
  *   1. Builds a fresh temp workspace via [[Workspace]].
  *   2. Writes files / yaml. Optionally tags content with a snippet name; tagged content is mirrored to [[snippetsRoot]] (`docs-snippets-from-tests/<name>`) so
  *      the docs site's `<Snippet path="..." />` can include the same files the tests run against.
  *   3. Bootstraps `Started` in-process and runs assertions.
  *
  * The snippets directory is git-tracked. CI can assert no diff (`git diff --exit-code docs-snippets-from-tests`) to catch drift between what tests exercise
  * and what the site renders.
  */
abstract class IntegrationTestHarness extends AnyFunSuite {
  protected val userPaths: UserPaths = UserPaths.fromAppDirs

  protected val logger0 = Loggers.decodeJsonStream(
    bleepLoggers.BLEEP_JSON_EVENT,
    Loggers
      .stdout(LogPatterns.interface(Some(Instant.now), noColor = false), disableProgress = true)
      .acquire()
      .value
      .withMinLogLevel(LogLevel.info)
  )

  protected val ec: ExecutionContextExecutor = ExecutionContext.global

  protected val lazyBleepBuild: Lazy[Started] =
    Lazy {
      val existing = BuildLoader.find(FileUtils.cwd).existing.orThrow
      val pre = Prebootstrapped(logger0, userPaths, BuildPaths(FileUtils.cwd, existing, model.BuildVariant.Normal), existing, ec)
      bootstrap.from(pre, ResolveProjects.InMemory, Nil, model.BleepConfig.default, CoursierResolver.Factory.default).orThrow
    }

  protected val testConfig: model.BleepConfig = model.BleepConfig(
    compileServerMode = Some(model.CompileServerMode.NewEachInvocation),
    authentications = None,
    logTiming = None,
    // Cap forked test-runner JVMs at 512m and bound parallelism — each IT spawns its own test
    // runner (and that test runner forks its own Main subprocess), so unbounded heaps × parallelism
    // × CI runner count quickly tops the GHA 16 GB budget. The matching cap on forked Mains lives
    // in [[Workspace.start]] via [[JvmRunner.CappedFork]].
    bspServerConfig = Some(
      model.BspServerConfig.default.copy(
        testRunnerMaxMemory = Some("512m")
      )
    ),
    remoteCacheCredentials = None
  )

  /** Prelude prepended to every test's bleep.yaml so build.bleep::* deps resolve to the in-memory bleep build. */
  protected val prelude: String =
    s"""$$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
       |$$version: dev
       |jvm:
       |  name: ${model.Jvm.graalvm.name}
       |""".stripMargin

  /** Where snippet files generated by tests are written. Tracked in git. */
  protected val snippetsRoot: Path = FileUtils.cwd / "docs-snippets-from-tests"

  /** Define an integration test.
    *
    * The body receives a [[Workspace]] for setup + assertions. Any content tagged via `ws.file(..., snippet = "...")` or `ws.yaml(..., snippet = "...")` is
    * mirrored to [[snippetsRoot]] after the body completes.
    */
  def integrationTest(testName: String)(body: Workspace => Assertion): Unit =
    test(testName) {
      val ws = new Workspace(testName, prelude, snippetsRoot, userPaths, logger0, ec, lazyBleepBuild, testConfig)
      try {
        val ret = body(ws)
        ws.commitSnippets()
        ret
      } finally ws.cleanup()
    }
}

/** A test workspace: a temp directory + a bleep.yaml + source files + an attached `Started`/`Commands` pair when [[start]] is called.
  *
  * Methods that take a `snippet` name mirror the file content into `<snippetsRoot>/<snippet>` so the docs site can include the same content via
  * `<Snippet path="<snippet>" />`.
  */
class Workspace(
    testName: String,
    prelude: String,
    snippetsRoot: Path,
    userPaths: UserPaths,
    parentLogger: ryddig.TypedLogger[?],
    ec: ExecutionContextExecutor,
    lazyBleepBuild: Lazy[Started],
    testConfig: model.BleepConfig
) {

  val root: Path = Files.createTempDirectory(s"bleep-doc-$testName-")

  private var rawYaml: Option[String] = None
  private val taggedSnippets: mutable.LinkedHashMap[String, String] = mutable.LinkedHashMap.empty
  private val staticAuth: mutable.LinkedHashMap[java.net.URI, model.AuthEntry] = mutable.LinkedHashMap.empty
  private var startedOpt: Option[(Started, Commands, TypedLogger[Array[Stored]])] = None

  /** Wire static HTTP basic auth for a resolver URI. The credentials end up in the [[model.BleepConfig]] passed to bootstrap, exactly the same path real users
    * configure via `~/.config/bleep/config.yaml`.
    */
  def setStaticAuth(uri: java.net.URI, user: String, password: String): Unit =
    staticAuth.update(uri, model.AuthEntry.Static(coursier.core.Authentication(user, password)))

  /** Write a source file under [[root]]. */
  def file(relPath: String, content: String): Unit =
    writeFile(relPath, content)

  /** Write a source file and mirror the same content to `<snippetsRoot>/<snippet>`. */
  def file(relPath: String, content: String, snippet: String): Unit = {
    writeFile(relPath, content)
    taggedSnippets.update(snippet, content)
  }

  /** Write the bleep.yaml. The schema/version/jvm prelude is prepended automatically. */
  def yaml(content: String): Unit = {
    rawYaml = Some(content)
    writeFile(BuildLoader.BuildFileName, prelude + content)
  }

  /** Write the bleep.yaml and mirror the user-facing content (without prelude) to `<snippetsRoot>/<snippet>`. The site sees a self-contained yaml since the
    * published `$schema` / `$version` / `jvm` lines are added back via [[snippetWithPrelude]] when the user wants the full file shown.
    */
  def yaml(content: String, snippet: String): Unit = {
    yaml(content)
    taggedSnippets.update(snippet, snippetWithPrelude(content))
  }

  /** Bootstrap `Started` for this workspace. Idempotent — repeated calls return the same instance. */
  def start(): (Started, Commands, TypedLogger[Array[Stored]]) =
    startedOpt match {
      case Some(s) => s
      case None    =>
        val storingLogger = ThreadSafeStoringLogger()
        val stdLogger = parentLogger.withContext("testName", testName)
        val existingBuild = BuildLoader.find(root).existing.orThrow
        val buildPaths = BuildPaths(cwd = root, existingBuild, model.BuildVariant.Normal)
        val effectiveConfig =
          if (staticAuth.isEmpty) testConfig
          else testConfig.copy(authentications = Some(model.Authentications(staticAuth.toMap)))
        val rawStarted = bootstrap
          .from(
            Prebootstrapped(storingLogger.zipWith(stdLogger), userPaths, buildPaths, existingBuild, ec),
            ResolveProjects.ReplaceBleepDependencies(lazyBleepBuild, BspServerClasspathSource.InProcess(InProcessBspServer.connect)),
            Nil,
            effectiveConfig,
            CoursierResolver.Factory.default
          )
          .orThrow
        // Swap in a capped-heap forked runner so when an IT calls `commands.run`, the forked Main
        // gets `-Xmx256m` instead of the JVM ergonomics default (~4 GB on a 16 GB CI runner).
        // ITs that explicitly set jvmOptions (e.g. JvmRunIT) keep their own values — the cap only
        // fires when the user hasn't constrained heap themselves.
        val started = rawStarted.withJvmRunner(JvmRunner.CappedFork("256m"))
        val commands = new Commands(started)
        val triple = (started, commands, storingLogger)
        startedOpt = Some(triple)
        triple
    }

  /** Compile every project in the build. Convenience wrapper around `commands.compile(allProjects)`. */
  def compileAll(): Unit = {
    val (started, commands, _) = start()
    commands.compile(started.build.explodedProjects.keys.toList)
  }

  /** Run `bleep new` against [[root]] to scaffold a fresh build for the given language. Writes bleep.yaml + Main + MainTest. Idempotent w.r.t. [[start]] — call
    * [[start]] afterwards to bootstrap.
    *
    * The scaffolded `bleep.yaml` gets `$version: dev` rather than the running bleep's current version, so the inner workspace's `bleep-test-runner` dep
    * resolves to `dev:<workspaceDir>` and short-circuits through `BleepDevDeps.resolveFromJvmClasspath` to the same `bleep-test-runner/classes` directory
    * already on this JVM's classpath. Without this, ITs would try to resolve `bleep-test-runner:1.0.0-MX` from Maven Central — which only works if that exact
    * release was published, and fails outright on CI runners where the running bleep version may be `0.0.0+...-SNAPSHOT` (no git tags).
    */
  def bleepNew(language: BuildCreateNew.Language, name: String): Unit = {
    val cmd = BuildCreateNew(
      logger = parentLogger.withContext("testName", testName),
      userPaths = userPaths,
      cwd = root,
      language = language,
      platforms = cats.data.NonEmptyList.of(model.PlatformId.Jvm),
      scalas = cats.data.NonEmptyList.of(model.VersionScala.Scala3),
      name = name,
      bleepVersion = model.BleepVersion.dev,
      coursierResolver = CoursierResolver.Factory.default
    )
    cmd.run().orThrow
  }

  /** Read a file written by [[bleepNew]] (or any other workspace setup) and tag it as a snippet. The content is mirrored to `<snippetsRoot>/<snippet>` when the
    * test body completes.
    *
    * For bleep.yaml content the in-test `$version: dev` is rewritten to the latest release tag so docs are copy-pasteable. Same trick as [[snippetWithPrelude]]
    * uses for the manually-authored prelude path.
    */
  def attachSnippet(relPath: String, snippet: String): Unit = {
    val source = root.resolve(relPath)
    val raw = Files.readString(source)
    val content = if (relPath.endsWith("bleep.yaml")) normalizeDevVersionForDocs(raw) else raw
    taggedSnippets.update(snippet, content)
  }

  private def normalizeDevVersionForDocs(yaml: String): String = {
    val release = model.BleepVersion.current.value.takeWhile(_ != '+')
    yaml.replaceFirst("(?m)^\\$version: dev$", s"\\$$version: $release")
  }

  /** Mirror `userYaml` (with the published `$schema` / `$version` / `jvm` prelude) to `<snippetsRoot>/<snippet>` without affecting the workspace bleep.yaml.
    * Use this when the in-test bleep.yaml needs different values than what the docs should show — e.g. a localhost test port versus a documented Artifactory
    * URL.
    */
  def attachSnippetYaml(snippet: String, userYaml: String): Unit =
    taggedSnippets.update(snippet, snippetWithPrelude(userYaml))

  /** Mirror every tagged snippet to `<snippetsRoot>/<snippet>`. Called by integrationTest after the body. */
  def commitSnippets(): Unit =
    taggedSnippets.foreach { case (name, content) =>
      val target = snippetsRoot.resolve(name)
      Option(target.getParent).foreach(Files.createDirectories(_))
      Files.writeString(target, content)
    }

  def cleanup(): Unit =
    try FileUtils.deleteDirectory(root)
    catch { case _: Throwable => () }

  private def writeFile(relPath: String, content: String): Unit = {
    val target = root.resolve(relPath)
    Option(target.getParent).foreach(Files.createDirectories(_))
    Files.writeString(target, content)
  }

  /** When the user wants to show the full bleep.yaml (with schema + version + jvm) we reconstruct it. The test body's yaml prelude uses `$version: dev`; for
    * the site we substitute the most recent release tag so docs are copy-pasteable. Dynver appends `+<commits>-<sha>-SNAPSHOT` after the tag — strip it.
    */
  private def snippetWithPrelude(userYaml: String): String = {
    val release = model.BleepVersion.current.value.takeWhile(_ != '+')
    val publishedPrelude =
      s"""$$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
         |$$version: $release
         |jvm:
         |  name: ${model.Jvm.graalvm.name}
         |""".stripMargin
    publishedPrelude + userYaml
  }
}
