package bleep

import bleep.internal.FileUtils
import bleep.mavenimport.{generateBuildFromMaven, parsePom, MavenFs, MavenImportOptions, MavenProject}
import bleep.testing.{GenBloopFiles, MavenRoundtrip, SnapshotTest, TemplateStats}
import coursier.paths.CoursierPaths
import io.circe.Codec
import io.circe.generic.semiauto.deriveCodec
import io.circe.syntax.EncoderOps
import org.scalatest.Assertion

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}
import scala.collection.immutable.SortedMap
import scala.concurrent.ExecutionContext

/** Imports real maven builds and checks the result, like [[IntegrationSnapshotTests]] does for sbt.
  *
  * What the import read from the maven build is recorded once (see [[MavenFs.Recording]]), together with the classpaths maven computed for every module, and
  * checked in as `input.json.gz`. After that the tests run without the build checked out and without maven.
  *
  * Recording runs maven in a clone of the build, with a local repository of its own inside the test folder - the global maven repository is never read or
  * written, and nothing is installed. `-am` builds the modules a module depends on in the same reactor, so their classes resolve from there.
  */
class MavenIntegrationSnapshotTests extends SnapshotTest {
  val userPaths = UserPaths.fromAppDirs

  /** Only paths. The os and architecture masks of [[absolutePaths]] would also rewrite generated sources, which are recorded too, and could not be undone */
  private val mavenPaths: model.Replacements =
    model.Replacements.ofReplacements(
      List(
        (CoursierPaths.cacheDirectory().toString, "<COURSIER>"),
        (CoursierPaths.archiveCacheDirectory().toString, "<COURSIER_ARC>"),
        (System.getProperty("user.dir"), "<BLEEP_GIT>"),
        (System.getProperty("user.home"), "<HOME>")
      )
    )

  private val jdk21: model.Jvm = model.Jvm("temurin:21", None)
  // feign's .mvn/jvm.config passes flags only newer jdks know
  private val jdk25: model.Jvm = model.Jvm("temurin:25", None)

  test("spring-petclinic") {
    testIn("spring-petclinic", "https://github.com/spring-projects/spring-petclinic.git", "818c4136e", jdk21, toolchains = Nil)
  }

  test("feign") {
    testIn(
      "feign",
      "https://github.com/OpenFeign/feign.git",
      "8c719937a",
      jdk25,
      // modules build their main code for java 8, 11 or 17, and tests for the latest java, all through maven toolchains
      toolchains =
        List("1.8" -> model.Jvm("liberica:8.0.452", None), "11" -> model.Jvm("temurin:11", None), "17" -> model.Jvm("temurin:17", None), "25" -> jdk25)
    )
  }

  test("dropwizard") {
    testIn("dropwizard", "https://github.com/dropwizard/dropwizard.git", "30f64bbd2", jdk21, toolchains = Nil)
  }

  // kotlin and java modules, compiled by kotlin-maven-plugin
  test("javalin") {
    testIn("javalin", "https://github.com/javalin/javalin.git", "20ba71b2", jdk21, toolchains = Nil)
  }

  // an annotation processor, and modules which run it
  test("mapstruct") {
    testIn("mapstruct", "https://github.com/mapstruct/mapstruct.git", "211b2be6", jdk21, toolchains = Nil)
  }

  // sources generated by javacc, and code built for java 8
  test("javaparser") {
    testIn("javaparser", "https://github.com/javaparser/javaparser.git", "2d5ce26ef", jdk21, toolchains = Nil)
  }

  /** @param jvm
    *   the jvm maven runs on
    * @param toolchains
    *   jdks a build asks for through maven toolchains, by the version it asks for
    */
  def testIn(project: String, repo: String, sha: String, jvm: model.Jvm, toolchains: List[(String, model.Jvm)]): Assertion = {
    val logger = logger0.withPath(project)
    val testFolder = outFolder / project
    val mavenBuildDir = testFolder / "maven-build"
    val inputPath = testFolder / "input.json.gz"
    val importedPath = testFolder / "imported"
    val bootstrappedPath = testFolder / "bootstrapped"

    val options = MavenImportOptions(
      ignoreWhenInferringTemplates = Set.empty,
      skipMvn = false,
      skipGeneratedResourcesScript = false,
      mvnPath = None,
      filtering = sbtimport.ImportFiltering.empty
    )

    val importedBuildLoader = BuildLoader.inDirectory(importedPath)
    val importedDestinationPaths = BuildPaths(cwd = FileUtils.TempDir, importedBuildLoader, model.BuildVariant.Normal)

    def runImport(fs: MavenFs, mavenProjects: List[MavenProject], dependencyList: Path): Map[Path, String] =
      generateBuildFromMaven(
        importedDestinationPaths,
        logger,
        options,
        model.BleepVersion.dev,
        bleepTasksVersion = model.BleepVersion("1.0.0-M14"),
        fs,
        mavenProjects,
        dependencyList
      )

    val input: MavenSnapshotInput =
      if (Files.exists(inputPath)) {
        val jsonText = new String(FileUtils.readGzippedBytes(inputPath), StandardCharsets.UTF_8)
        io.circe.parser.decode[MavenSnapshotInput](jsonText) match {
          case Left(circeError) => throw new BleepException.InvalidJson(inputPath, circeError)
          case Right(templated) => templated.mapStrings(mavenPaths.fill.string)
        }
      } else {
        val recorded = record(logger, repo, sha, jvm, toolchains, testFolder, mavenBuildDir, runImport)
        FileUtils.writeGzippedBytes(inputPath, recorded.mapStrings(mavenPaths.templatize.string).asJson.spaces2.getBytes(StandardCharsets.UTF_8))
        recorded
      }

    val fs = new MavenFs.Replay(input.fs)
    val mavenProjects = parsePom(fs, Path.of(input.effectivePom))
    val buildFiles = runImport(fs, mavenProjects, Path.of(input.dependencyList))

    writeAndCompare(importedDestinationPaths.buildDir, buildFiles.map { case (p, s) => (p, mavenPaths.templatize.string(s)) }, logger).discard()

    val bootstrappedDestinationPaths = BuildPaths(cwd = FileUtils.TempDir, BuildLoader.inDirectory(bootstrappedPath), model.BuildVariant.Normal)
    val existingImportedBuildLoader = BuildLoader.Existing(importedBuildLoader.bleepYaml)

    TestResolver.withFactory(isCi, testFolder, absolutePaths) { testResolver =>
      val pre = Prebootstrapped(logger, userPaths, bootstrappedDestinationPaths, existingImportedBuildLoader, ExecutionContext.global)
      val started = bootstrap.from(pre, ResolveProjects.InMemory, rewrites = Nil, model.BleepConfig.default, testResolver).orThrow

      val resolved = started.resolvedProjects.collect {
        case (crossName, lazyResolved) if crossName.name.value != "scripts" => (crossName, lazyResolved.forceGet)
      }
      val roundtrip = MavenRoundtrip.report(
        mavenProjects,
        input.classpaths.map { case (dir, cps) => (Path.of(dir), cps) },
        resolved,
        mavenBuildDir,
        started.buildPaths.buildDir
      )
      val report = List("# template inference", TemplateStats.render(buildFiles(importedDestinationPaths.bleepYamlFile)), "", "# roundtrip", roundtrip)
      val reportPath = testFolder / "import-report.txt"
      writeAndCompare(reportPath, Map(reportPath -> absolutePaths.templatize.string(report.mkString("", "\n", "\n"))), logger).discard()

      val generatedBloopFiles: Map[Path, String] =
        GenBloopFiles.encodedFiles(GenBloopFiles.defaultBloopFilePath(bootstrappedDestinationPaths), started.resolvedProjects)

      // note, keep last. locally it "succeeds" with a `pending`
      writeAndCompare(bootstrappedPath, generatedBloopFiles.map { case (p, s) => (p, absolutePaths.templatize.string(s)) }, logger)
    }
  }

  /** Runs maven in a clone of the build, then imports it once, recording everything the import reads */
  private def record(
      logger: ryddig.Logger,
      repo: String,
      sha: String,
      jvm: model.Jvm,
      toolchains: List[(String, model.Jvm)],
      testFolder: Path,
      mavenBuildDir: Path,
      runImport: (MavenFs, List[MavenProject], Path) => Map[Path, String]
  ): MavenSnapshotInput = {
    val cliOut = cli.Out.ViaLogger(logger)
    if (!Files.exists(mavenBuildDir)) {
      Files.createDirectories(testFolder)
      cli("git clone", testFolder, List("git", "clone", repo, mavenBuildDir.getFileName.toString), logger, cliOut).discard()
    } else cli("git fetch", mavenBuildDir, List("git", "fetch"), logger, cliOut).discard()
    cli("git checkout", mavenBuildDir, List("git", "checkout", "--detach", sha), logger, cliOut).discard()

    // unpacking a jdk logs through slf4j
    bleep.internal.Slf4jBridge.install(logger)
    val fetchJvm = new FetchJvm(Some(userPaths.resolveJvmCacheDir), new BleepCacheLogger(logger), ExecutionContext.global)
    val javaHome = fetchJvm(jvm).javaBin.getParent.getParent
    val env = List("JAVA_HOME" -> javaHome.toString)

    // toolchains the build asks for, declared here rather than in ~/.m2/toolchains.xml
    val toolchainArgs: List[String] =
      if (toolchains.isEmpty) Nil
      else {
        val jdks = toolchains.map { case (version, toolchainJvm) =>
          val home = fetchJvm(toolchainJvm).javaBin.getParent.getParent
          s"""  <toolchain>
             |    <type>jdk</type>
             |    <provides><version>$version</version></provides>
             |    <configuration><jdkHome>$home</jdkHome></configuration>
             |  </toolchain>""".stripMargin
        }
        val file = testFolder / "maven-toolchains.xml"
        Files.writeString(file, jdks.mkString("<toolchains>\n", "\n", "\n</toolchains>\n"))
        List("-t", file.toString)
      }

    // a local repository of its own, so the global maven repository is neither read nor written
    val mvn = List("mvn", "-B", s"-Dmaven.repo.local=${testFolder / "maven-repo"}") ++ toolchainArgs
    // outside the build, where `clean` doesn't reach
    val effectivePom = testFolder / "maven-effective-pom.xml"

    cli("mvn effective-pom", mavenBuildDir, mvn ++ List("help:effective-pom", s"-Doutput=$effectivePom"), logger, cliOut, env = env).discard()

    // what maven resolves for every module, which the import reads (see `runMaven`)
    val dependencyList = testFolder / "maven-dependency-list.txt"
    val listed = cli("mvn dependency:list", mavenBuildDir, mvn ++ List("-am", "-DskipTests", "clean", "package", "dependency:list"), logger, cliOut, env = env)
    Files.writeString(dependencyList, listed.stdout.mkString("\n"))
    // builds, since maven resolves a module another module depends on from the reactor only once it has been built in the same session
    // by artifactId. read from maven's output rather than a file: a file in the module directory trips a build's checks (feign's license headers), and one
    // in target/ may be removed again by a plugin
    def mavenClasspaths(scope: String): Map[String, List[String]] = {
      val lines = cli(
        s"mvn classpath $scope",
        mavenBuildDir,
        mvn ++ List(
          "-am",
          "-DskipTests",
          // from scratch: the build was packaged for the dependency list already, and not every plugin runs twice (javalin's moditect refuses a jar it made
          // modular itself)
          "clean",
          // not just test-compile: some modules depend on what a sibling produces when it is packaged (feign's jakarta transformed jaxrs2)
          "package",
          "dependency:build-classpath",
          s"-DincludeScope=$scope"
        ),
        logger,
        cliOut,
        env = env
      ).stdout.toList
      MavenIntegrationSnapshotTests.parseClasspaths(lines)
    }
    val compile = mavenClasspaths("compile")
    val test = mavenClasspaths("test")

    val recording = new MavenFs.Recording(MavenFs.Real)
    val mavenProjects = parsePom(recording, effectivePom)
    runImport(recording, mavenProjects, dependencyList).discard()

    def classpathOf(scoped: Map[String, List[String]], module: MavenProject, scope: String): List[String] =
      scoped.getOrElse(module.artifactId, sys.error(s"maven printed no $scope classpath for ${module.artifactId}"))

    val classpaths = mavenProjects
      .filter(_.packaging != "pom")
      .map { module =>
        (module.directory.toString, MavenRoundtrip.Classpaths(classpathOf(compile, module, "compile"), classpathOf(test, module, "test")))
      }

    MavenSnapshotInput(effectivePom.toString, dependencyList.toString, recording.recorded, SortedMap.from(classpaths))
  }
}

object MavenIntegrationSnapshotTests {

  private val Header = """.*--- dependency:[^:]+:build-classpath \(default-cli\) @ (\S+) ---.*""".r

  /** `mvn dependency:build-classpath` logs `Dependencies classpath:` and the classpath on the next line, after a header naming the module */
  def parseClasspaths(lines: List[String]): Map[String, List[String]] = {
    val result = Map.newBuilder[String, List[String]]
    var module: Option[String] = None
    lines.zip(lines.drop(1) :+ "").foreach { case (line, next) =>
      line match {
        case Header(artifactId)                              => module = Some(artifactId)
        case l if l.trim.endsWith("Dependencies classpath:") =>
          val artifactId = module.getOrElse(sys.error(s"a classpath before any module header: $next"))
          result += (artifactId -> next.trim.split(java.io.File.pathSeparator).toList.filter(_.nonEmpty))
        case _ => ()
      }
    }
    result.result()
  }
}

/** What a maven import of a real build read, and the classpaths maven computed for it */
case class MavenSnapshotInput(
    effectivePom: String,
    dependencyList: String,
    fs: MavenFs.Recorded,
    classpaths: SortedMap[String, MavenRoundtrip.Classpaths]
) {
  def mapStrings(f: String => String): MavenSnapshotInput =
    MavenSnapshotInput(
      effectivePom = f(effectivePom),
      dependencyList = f(dependencyList),
      fs = fs.mapStrings(f),
      classpaths = classpaths.map { case (dir, cps) => (f(dir), MavenRoundtrip.Classpaths(cps.compile.map(f), cps.test.map(f))) }
    )
}

object MavenSnapshotInput {
  implicit val codec: Codec.AsObject[MavenSnapshotInput] = deriveCodec
}
