package bleep

import bleep.internal.FileUtils

import java.nio.file.{Files, Path}
import scala.jdk.CollectionConverters.*

class SpringBootMyappIT extends IntegrationTestHarness {

  integrationTest("spring-boot-myapp compiles, tests, and packages an executable fat JAR") { ws =>
    // bleep.yaml has to be authored inline because the harness needs `$version: dev` in the
    // prelude so `build.bleep:bleep-plugin-spring-boot:${BLEEP_VERSION}` resolves to the
    // in-memory bleep build via ResolveProjects.ReplaceBleepDependencies (rather than
    // pulling a stale release from Maven Central).
    ws.yaml(
      snippet = "spring-boot-myapp/bleep.yaml",
      content = """projects:
                  |  myapp:
                  |    dependencies:
                  |      - org.springframework.boot:spring-boot-starter-web:3.4.0
                  |      - org.springframework.boot:spring-boot-starter-jdbc:3.4.0
                  |      - org.springframework.boot:spring-boot-starter-actuator:3.4.0
                  |      - org.duckdb:duckdb_jdbc:1.1.3
                  |    extends:
                  |      - template-common
                  |    platform:
                  |      mainClass: com.example.myapp.MyApp
                  |    sourcegen:
                  |      - main: bleep.plugin.springboot.SpringBootBuildInfo
                  |        project: scripts
                  |  myapp-test:
                  |    dependencies:
                  |      - org.springframework.boot:spring-boot-starter-test:3.4.0
                  |    dependsOn: myapp
                  |    extends:
                  |      - template-common
                  |    isTestProject: true
                  |  scripts:
                  |    dependencies:
                  |      - build.bleep:bleep-plugin-spring-boot:${BLEEP_VERSION}
                  |    java:
                  |      options: -proc:none --release 17
                  |    platform:
                  |      name: jvm
                  |scripts:
                  |  run-myapp-dev:
                  |    main: scripts.RunMyappDev
                  |    project: scripts
                  |  run-myapp-prod:
                  |    main: scripts.RunMyappProd
                  |    project: scripts
                  |  package-myapp:
                  |    main: scripts.PackageMyapp
                  |    project: scripts
                  |templates:
                  |  template-common:
                  |    java:
                  |      options: -proc:none --release 17
                  |    platform:
                  |      name: jvm
                  |""".stripMargin
    )

    // The other 15 files (sources, resources, scripts) come straight from the
    // already-committed fixture — copied into the workspace and re-tagged as snippets so the
    // mirror loop produces no diff against what's in git.
    val fixtureRoot = FileUtils.cwd.resolve("docs-snippets-from-tests/spring-boot-myapp")
    copyFixtureInto(ws, fixtureRoot, skip = "bleep.yaml")

    val (started, commands, storingLogger) = ws.start()

    commands.compile(List(named("myapp")))

    // The substantive proof. The 6-test suite exercises:
    //   * Spring Boot startup with @SpringBootTest and the test profile.
    //   * The wired beans (ItemController → ItemService → ItemRepository).
    //   * DuckDB via spring-boot-starter-jdbc + JdbcTemplate + INSERT...RETURNING id.
    //   * spring-boot-starter-test (MockMvc) hitting the controller without binding a port.
    //   * SpringBootBuildInfo sourcegen ran during compile (Actuator /info would pick this up
    //     at runtime; we just verify the file was generated by the compile step succeeding).
    commands.test(
      projects = List(named("myapp-test")),
      watch = false,
      only = None,
      exclude = None
    )

    // package-myapp is exercised manually (see the Spring Boot tutorial); we don't drive it
    // from the IT because the harness's JvmRunner.InProcess runner has a known limitation
    // around bleepscript.Launcher reading sun.java.command for the BleepScript main class,
    // which gets clobbered by the test runner's prior in-process main. Forking the JVM would
    // work but the harness deliberately runs in-process for GHA memory reasons.

    succeed
  }

  /** Walks every file under `fixtureRoot` (excluding the file named by `skip`), reads the content, writes it into the workspace at the same relative path, and
    * tags it as a snippet at `spring-boot-myapp/<relPath>` so the harness's mirror loop overwrites the fixture with the same bytes (no-op).
    */
  private def copyFixtureInto(ws: Workspace, fixtureRoot: Path, skip: String): Unit =
    Files
      .walk(fixtureRoot)
      .iterator()
      .asScala
      .filter(Files.isRegularFile(_))
      .filterNot(p => p.toString.contains("/.bleep/") || p.toString.contains("/build/"))
      .foreach { src =>
        val relPath = fixtureRoot.relativize(src).toString
        if (relPath != skip) {
          val content = Files.readString(src)
          ws.file(relPath, content, snippet = s"spring-boot-myapp/$relPath")
        }
      }

  private def named(name: String): model.CrossProjectName =
    model.CrossProjectName(model.ProjectName(name), None)
}
