// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scala.meta.internal.semanticdb

@SerialVersionUID(0L)
final case class Documentation(
    message: _root_.scala.Predef.String = "",
    format: scala.meta.internal.semanticdb.Documentation.Format = scala.meta.internal.semanticdb.Documentation.Format.HTML
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Documentation] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = format.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(2, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = format.value
        if (__v != 0) {
          _output__.writeEnum(2, __v)
        }
      };
    }
    def withMessage(__v: _root_.scala.Predef.String): Documentation = copy(message = __v)
    def withFormat(__v: scala.meta.internal.semanticdb.Documentation.Format): Documentation = copy(format = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = format.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(message)
        case 2 => _root_.scalapb.descriptors.PEnum(format.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: scala.meta.internal.semanticdb.Documentation.type = scala.meta.internal.semanticdb.Documentation
    // @@protoc_insertion_point(GeneratedMessage[scala.meta.internal.semanticdb.Documentation])
}

object Documentation extends scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb.Documentation] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb.Documentation] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): scala.meta.internal.semanticdb.Documentation = {
    var __message: _root_.scala.Predef.String = ""
    var __format: scala.meta.internal.semanticdb.Documentation.Format = scala.meta.internal.semanticdb.Documentation.Format.HTML
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __message = _input__.readStringRequireUtf8()
        case 16 =>
          __format = scala.meta.internal.semanticdb.Documentation.Format.fromValue(_input__.readEnum())
        case tag => _input__.skipField(tag)
      }
    }
    scala.meta.internal.semanticdb.Documentation(
        message = __message,
        format = __format
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[scala.meta.internal.semanticdb.Documentation] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      scala.meta.internal.semanticdb.Documentation(
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        format = scala.meta.internal.semanticdb.Documentation.Format.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(scala.meta.internal.semanticdb.Documentation.Format.HTML.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SemanticdbProto.javaDescriptor.getMessageTypes().get(40)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SemanticdbProto.scalaDescriptor.messages(40)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 2 => scala.meta.internal.semanticdb.Documentation.Format
    }
  }
  lazy val defaultInstance = scala.meta.internal.semanticdb.Documentation(
    message = "",
    format = scala.meta.internal.semanticdb.Documentation.Format.HTML
  )
  sealed abstract class Format(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = scala.meta.internal.semanticdb.Documentation.Format
    type RecognizedType = scala.meta.internal.semanticdb.Documentation.Format.Recognized
    def isHtml: _root_.scala.Boolean = false
    def isMarkdown: _root_.scala.Boolean = false
    def isJavadoc: _root_.scala.Boolean = false
    def isScaladoc: _root_.scala.Boolean = false
    def isKdoc: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Format] = scala.meta.internal.semanticdb.Documentation.Format
    final def asRecognized: _root_.scala.Option[scala.meta.internal.semanticdb.Documentation.Format.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[scala.meta.internal.semanticdb.Documentation.Format.Recognized])
  }
  
  object Format extends _root_.scalapb.GeneratedEnumCompanion[Format] {
    sealed trait Recognized extends Format
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Format] = this
    
    @SerialVersionUID(0L)
    case object HTML extends Format(0) with Format.Recognized {
      val index = 0
      val name = "HTML"
      override def isHtml: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object MARKDOWN extends Format(1) with Format.Recognized {
      val index = 1
      val name = "MARKDOWN"
      override def isMarkdown: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object JAVADOC extends Format(2) with Format.Recognized {
      val index = 2
      val name = "JAVADOC"
      override def isJavadoc: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object SCALADOC extends Format(3) with Format.Recognized {
      val index = 3
      val name = "SCALADOC"
      override def isScaladoc: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object KDOC extends Format(4) with Format.Recognized {
      val index = 4
      val name = "KDOC"
      override def isKdoc: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Format(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(HTML, MARKDOWN, JAVADOC, SCALADOC, KDOC)
    def fromValue(__value: _root_.scala.Int): Format = __value match {
      case 0 => HTML
      case 1 => MARKDOWN
      case 2 => JAVADOC
      case 3 => SCALADOC
      case 4 => KDOC
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = scala.meta.internal.semanticdb.Documentation.javaDescriptor.getEnumTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = scala.meta.internal.semanticdb.Documentation.scalaDescriptor.enums(0)
  }
  implicit class DocumentationLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb.Documentation]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, scala.meta.internal.semanticdb.Documentation](_l) {
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def format: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb.Documentation.Format] = field(_.format)((c_, f_) => c_.copy(format = f_))
  }
  final val MESSAGE_FIELD_NUMBER = 1
  final val FORMAT_FIELD_NUMBER = 2
  def of(
    message: _root_.scala.Predef.String,
    format: scala.meta.internal.semanticdb.Documentation.Format
  ): _root_.scala.meta.internal.semanticdb.Documentation = _root_.scala.meta.internal.semanticdb.Documentation(
    message,
    format
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[scala.meta.internal.semanticdb.Documentation])
}
