
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForImporterPortable extends BleepCodegenScript("GenerateForImporterPortable") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("importer-portable").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package org.scalablytyped.converter.internal
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "3a4686a8ee2547478c12a30ee98ac7d8f12d0a65". */
      |  val gitSha: String = "3a4686a8ee2547478c12a30ee98ac7d8f12d0a65"
      |  /** The value is "1.0.0-beta41+5-3a4686a8+20230529-1301-SNAPSHOT". */
      |  val version: String = "1.0.0-beta41+5-3a4686a8+20230529-1301-SNAPSHOT"
      |  override val toString: String = {
      |    "gitSha: %s, version: %s".format(
      |      gitSha, version
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}