spring.application.name=myapp
spring.datasource.url=jdbc:duckdb:
spring.datasource.driver-class-name=org.duckdb.DuckDBDriver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
management.endpoints.web.exposure.include=info,health
