
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForCommon extends BleepCodegenScript("GenerateForCommon") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set(s"""|common@native213""".stripMargin, s"""|common@js213""".stripMargin, s"""|common@jvm211""".stripMargin, s"""|common@native212""".stripMargin, s"""|common@js212""".stripMargin, s"""|common@jvm212""".stripMargin, s"""|common@jvm213""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package scala.meta.internal
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "4.13.7-SNAPSHOT". */
      |  val version: String = "4.13.7-SNAPSHOT"
      |  override val toString: String = {
      |    "version: %s".format(
      |      version
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}