
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForZioStreams extends BleepCodegenScript("GenerateForZioStreams") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set(s"""|zio-streams@js213""".stripMargin, s"""|zio-streams@jvm213""".stripMargin, s"""|zio-streams@native213""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package zio.stream
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "dev.zio". */
      |  final val organization = "dev.zio"
      |  /** The value is "zio-streams". */
      |  final val moduleName = "zio-streams"
      |  /** The value is "zio-streams". */
      |  final val name = "zio-streams"
      |  /** The value is "2.1.26+231-18e9a918-SNAPSHOT". */
      |  final val version = "2.1.26+231-18e9a918-SNAPSHOT"
      |  /** The value is "2.13.18". */
      |  final val scalaVersion = "2.13.18"
      |  /** The value is "1.13.0". */
      |  final val sbtVersion = "1.13.0"
      |  /** The value is true. */
      |  final val isSnapshot = true
      |  /** The value is false. */
      |  final val optimizationsEnabled = false
      |  override val toString: String = {
      |    import _root_.scala.StringContext
      |    s"organization: $${organization}, moduleName: $${moduleName}, name: $${name}, version: $${version}, scalaVersion: $${scalaVersion}, sbtVersion: $${sbtVersion}, isSnapshot: $${isSnapshot}, optimizationsEnabled: $${optimizationsEnabled}"
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|zio-streams@js3""".stripMargin, s"""|zio-streams@jvm3""".stripMargin, s"""|zio-streams@native3""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package zio.stream
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "dev.zio". */
      |  final val organization = "dev.zio"
      |  /** The value is "zio-streams". */
      |  final val moduleName = "zio-streams"
      |  /** The value is "zio-streams". */
      |  final val name = "zio-streams"
      |  /** The value is "2.1.26+231-18e9a918-SNAPSHOT". */
      |  final val version = "2.1.26+231-18e9a918-SNAPSHOT"
      |  /** The value is "3.3.8". */
      |  final val scalaVersion = "3.3.8"
      |  /** The value is "1.13.0". */
      |  final val sbtVersion = "1.13.0"
      |  /** The value is true. */
      |  final val isSnapshot = true
      |  /** The value is false. */
      |  final val optimizationsEnabled = false
      |  override val toString: String = {
      |    import _root_.scala.StringContext
      |    s"organization: $${organization}, moduleName: $${moduleName}, name: $${name}, version: $${version}, scalaVersion: $${scalaVersion}, sbtVersion: $${sbtVersion}, isSnapshot: $${isSnapshot}, optimizationsEnabled: $${optimizationsEnabled}"
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|zio-streams@js212""".stripMargin, s"""|zio-streams@jvm212""".stripMargin, s"""|zio-streams@native212""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package zio.stream
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "dev.zio". */
      |  final val organization = "dev.zio"
      |  /** The value is "zio-streams". */
      |  final val moduleName = "zio-streams"
      |  /** The value is "zio-streams". */
      |  final val name = "zio-streams"
      |  /** The value is "2.1.26+231-18e9a918-SNAPSHOT". */
      |  final val version = "2.1.26+231-18e9a918-SNAPSHOT"
      |  /** The value is "2.12.21". */
      |  final val scalaVersion = "2.12.21"
      |  /** The value is "1.13.0". */
      |  final val sbtVersion = "1.13.0"
      |  /** The value is true. */
      |  final val isSnapshot = true
      |  /** The value is false. */
      |  final val optimizationsEnabled = false
      |  override val toString: String = {
      |    import _root_.scala.StringContext
      |    s"organization: $${organization}, moduleName: $${moduleName}, name: $${name}, version: $${version}, scalaVersion: $${scalaVersion}, sbtVersion: $${sbtVersion}, isSnapshot: $${isSnapshot}, optimizationsEnabled: $${optimizationsEnabled}"
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}