package bleep.test.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import java.io.OutputStream
import java.nio.file.Files
import java.nio.file.Paths

/**
 * Tiny deterministic KSP processor used by bleep's integration tests. Three annotations:
 *
 * - `@GenerateKotlin(suffix)` emits a Kotlin class `<Original><suffix>` next to the source.
 * - `@GenerateJava(suffix)` emits a Java class `<Original><suffix>` so the mixed-compile path has
 *   something deterministic to round-trip through javac.
 * - `@ThrowOnMe` causes the processor to throw on `process()`; lets bleep tests exercise the
 *   processor-error path.
 *
 * Side-effect signal: each `process()` call appends a line to the file path passed via `apoption
 * bleep.test.ksp.log=<path>`. Tests count lines to verify invocation behaviour (e.g. that a no-op
 * recompile does not re-run the processor).
 */
class ToyProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        ToyProcessor(environment.codeGenerator, environment.options)
}

class ToyProcessor(
    private val codeGenerator: CodeGenerator,
    private val options: Map<String, String>,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        options[LOG_OPTION]?.let { p ->
            val path = Paths.get(p)
            Files.createDirectories(path.parent)
            Files.write(
                path,
                listOf("process"),
                java.nio.charset.StandardCharsets.UTF_8,
                java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.APPEND,
            )
        }

        val throwTargets =
            resolver
                .getSymbolsWithAnnotation(THROW_ON_ME)
                .filterIsInstance<KSClassDeclaration>()
                .toList()
        if (throwTargets.isNotEmpty()) {
            throw RuntimeException(
                "ToyProcessor: @ThrowOnMe encountered on ${throwTargets.first().simpleName.asString()}"
            )
        }

        resolver
            .getSymbolsWithAnnotation(GENERATE_KOTLIN)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { klass -> emitKotlin(klass) }

        resolver
            .getSymbolsWithAnnotation(GENERATE_JAVA)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { klass -> emitJava(klass) }

        return emptyList()
    }

    private fun emitKotlin(klass: KSClassDeclaration) {
        val suffix = readSuffix(klass, "GenerateKotlin") ?: return
        val pkg = klass.packageName.asString()
        val name = klass.simpleName.asString()
        val genName = name + suffix
        val file = klass.containingFile ?: return
        val out: OutputStream =
            codeGenerator.createNewFile(Dependencies(false, file), pkg, genName, "kt")
        out.bufferedWriter().use { w ->
            if (pkg.isNotEmpty()) {
                w.append("package ").append(pkg).append("\n\n")
            }
            w.append("// Generated by bleep ToyProcessor from ").append(name).append("\n")
            w.append("class ")
                .append(genName)
                .append(" { fun originalName(): String = \"")
                .append(name)
                .append("\" }\n")
        }
    }

    private fun emitJava(klass: KSClassDeclaration) {
        val suffix = readSuffix(klass, "GenerateJava") ?: return
        val pkg = klass.packageName.asString()
        val name = klass.simpleName.asString()
        val genName = name + suffix
        val file = klass.containingFile ?: return
        val out: OutputStream =
            codeGenerator.createNewFile(Dependencies(false, file), pkg, genName, "java")
        out.bufferedWriter().use { w ->
            if (pkg.isNotEmpty()) {
                w.append("package ").append(pkg).append(";\n\n")
            }
            w.append("// Generated by bleep ToyProcessor from ").append(name).append("\n")
            w.append("public final class ").append(genName).append(" {\n")
            w.append("  public static String originalName() { return \"")
                .append(name)
                .append("\"; }\n")
            w.append("}\n")
        }
    }

    private fun readSuffix(klass: KSClassDeclaration, simpleAnnotationName: String): String? {
        val ann =
            klass.annotations.firstOrNull { it.shortName.asString() == simpleAnnotationName }
                ?: return null
        val arg = ann.arguments.firstOrNull { it.name?.asString() == "suffix" } ?: return null
        return arg.value as? String
    }

    companion object {
        private const val GENERATE_KOTLIN = "bleep.test.ksp.GenerateKotlin"
        private const val GENERATE_JAVA = "bleep.test.ksp.GenerateJava"
        private const val THROW_ON_ME = "bleep.test.ksp.ThrowOnMe"
        private const val LOG_OPTION = "bleep.test.ksp.log"
    }
}
