// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scala.meta.internal.semanticidx

@SerialVersionUID(0L)
final case class Indexes(
    indexes: _root_.scala.Seq[scala.meta.internal.semanticidx.Index] = _root_.scala.Seq.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Indexes] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      indexes.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      indexes.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
    }
    def clearIndexes = copy(indexes = _root_.scala.Seq.empty)
    def addIndexes(__vs: scala.meta.internal.semanticidx.Index *): Indexes = addAllIndexes(__vs)
    def addAllIndexes(__vs: Iterable[scala.meta.internal.semanticidx.Index]): Indexes = copy(indexes = indexes ++ __vs)
    def withIndexes(__v: _root_.scala.Seq[scala.meta.internal.semanticidx.Index]): Indexes = copy(indexes = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => indexes
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(indexes.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: scala.meta.internal.semanticidx.Indexes.type = scala.meta.internal.semanticidx.Indexes
    // @@protoc_insertion_point(GeneratedMessage[scala.meta.internal.semanticidx.Indexes])
}

object Indexes extends scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticidx.Indexes] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticidx.Indexes] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): scala.meta.internal.semanticidx.Indexes = {
    val __indexes: _root_.scala.collection.immutable.VectorBuilder[scala.meta.internal.semanticidx.Index] = new _root_.scala.collection.immutable.VectorBuilder[scala.meta.internal.semanticidx.Index]
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __indexes += _root_.scalapb.LiteParser.readMessage[scala.meta.internal.semanticidx.Index](_input__)
        case tag => _input__.skipField(tag)
      }
    }
    scala.meta.internal.semanticidx.Indexes(
        indexes = __indexes.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[scala.meta.internal.semanticidx.Indexes] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      scala.meta.internal.semanticidx.Indexes(
        indexes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[scala.meta.internal.semanticidx.Index]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SemanticidxProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SemanticidxProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = scala.meta.internal.semanticidx.Index
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = scala.meta.internal.semanticidx.Indexes(
    indexes = _root_.scala.Seq.empty
  )
  implicit class IndexesLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticidx.Indexes]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, scala.meta.internal.semanticidx.Indexes](_l) {
    def indexes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[scala.meta.internal.semanticidx.Index]] = field(_.indexes)((c_, f_) => c_.copy(indexes = f_))
  }
  final val INDEXES_FIELD_NUMBER = 1
  def of(
    indexes: _root_.scala.Seq[scala.meta.internal.semanticidx.Index]
  ): _root_.scala.meta.internal.semanticidx.Indexes = _root_.scala.meta.internal.semanticidx.Indexes(
    indexes
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[scala.meta.internal.semanticidx.Indexes])
}
