
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForTapirCodegen extends BleepCodegenScript("GenerateForTapirCodegen") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set(s"""|tapir-codegen@jvm212""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package sttp.tapir.codegen
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "tapir-codegen". */
      |  val name: String = "tapir-codegen"
      |  /** The value is "1.13.32+1-918a0741-SNAPSHOT". */
      |  val version: String = "1.13.32+1-918a0741-SNAPSHOT"
      |  /** The value is "2.12.21". */
      |  val scalaVersion: String = "2.12.21"
      |  /** The value is "1.13.0". */
      |  val sbtVersion: String = "1.13.0"
      |  override val toString: String = {
      |    import _root_.scala.StringContext
      |    s"name: $${name}, version: $${version}, scalaVersion: $${scalaVersion}, sbtVersion: $${sbtVersion}"
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|tapir-codegen@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BuildInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package sttp.tapir.codegen
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "tapir-codegen". */
      |  val name: String = "tapir-codegen"
      |  /** The value is "1.13.32+1-918a0741-SNAPSHOT". */
      |  val version: String = "1.13.32+1-918a0741-SNAPSHOT"
      |  /** The value is "3.3.8". */
      |  val scalaVersion: String = "3.3.8"
      |  /** The value is "1.13.0". */
      |  val sbtVersion: String = "1.13.0"
      |  override val toString: String = {
      |    import _root_.scala.StringContext
      |    s"name: $${name}, version: $${version}, scalaVersion: $${scalaVersion}, sbtVersion: $${sbtVersion}"
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}