
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForTapirCodegen extends BleepCodegenScript("GenerateForTapirCodegen") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("tapir-codegen").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package sttp.tapir.codegen
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "tapir-codegen". */
      |  val name: String = "tapir-codegen"
      |  /** The value is "1.11.34+0-fdf0f99a+20250622-0021-SNAPSHOT". */
      |  val version: String = "1.11.34+0-fdf0f99a+20250622-0021-SNAPSHOT"
      |  /** The value is "2.12.20". */
      |  val scalaVersion: String = "2.12.20"
      |  /** The value is "1.11.0". */
      |  val sbtVersion: String = "1.11.0"
      |  override val toString: String = {
      |    "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s".format(
      |      name, version, scalaVersion, sbtVersion
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}