// $COVERAGE-OFF$
package sttp.tapir.codegen

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "tapir-codegen". */
  val name: String = "tapir-codegen"
  /** The value is "1.13.32+1-918a0741-SNAPSHOT". */
  val version: String = "1.13.32+1-918a0741-SNAPSHOT"
  /** The value is "2.12.21". */
  val scalaVersion: String = "2.12.21"
  /** The value is "1.13.0". */
  val sbtVersion: String = "1.13.0"
  override val toString: String = {
    import _root_.scala.StringContext
    s"name: ${name}, version: ${version}, scalaVersion: ${scalaVersion}, sbtVersion: ${sbtVersion}"
  }
}
// $COVERAGE-ON$
