
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForPekkoActor extends BleepCodegenScript("GenerateForPekkoActor") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|org/apache/pekko/Version.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|package org.apache.pekko
      |
      |object Version {
      |  val current: String = "2.0.0-M4+81-c2bc0f1c-SNAPSHOT"
      |}
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|org/apache/pekko/japi/function/Functions.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// auto-generated by sbt-boilerplate
      |/*
      | * Licensed to the Apache Software Foundation (ASF) under one or more
      | * license agreements; and to You under the Apache License, version 2.0:
      | *
      | *   https://www.apache.org/licenses/LICENSE-2.0
      | *
      | * This file is part of the Apache Pekko project, which was derived from Akka.
      | */
      |
      |/*
      | * Copyright (C) 2015-2022 Lightbend Inc. <https://www.lightbend.com>
      | */
      |
      |package org.apache.pekko.japi.function
      |
      |import scala.annotation.nowarn
      |
      |/**
      | * A Function interface. Used to create 3-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function3[-T1, -T2, -T3, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3): R
      |}
      |
      |/**
      | * A Function interface. Used to create 4-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function4[-T1, -T2, -T3, -T4, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4): R
      |}
      |
      |/**
      | * A Function interface. Used to create 5-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function5[-T1, -T2, -T3, -T4, -T5, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5): R
      |}
      |
      |/**
      | * A Function interface. Used to create 6-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function6[-T1, -T2, -T3, -T4, -T5, -T6, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6): R
      |}
      |
      |/**
      | * A Function interface. Used to create 7-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function7[-T1, -T2, -T3, -T4, -T5, -T6, -T7, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7): R
      |}
      |
      |/**
      | * A Function interface. Used to create 8-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function8[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8): R
      |}
      |
      |/**
      | * A Function interface. Used to create 9-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function9[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9): R
      |}
      |
      |/**
      | * A Function interface. Used to create 10-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function10[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10): R
      |}
      |
      |/**
      | * A Function interface. Used to create 11-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function11[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11): R
      |}
      |
      |/**
      | * A Function interface. Used to create 12-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function12[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12): R
      |}
      |
      |/**
      | * A Function interface. Used to create 13-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function13[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13): R
      |}
      |
      |/**
      | * A Function interface. Used to create 14-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function14[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14): R
      |}
      |
      |/**
      | * A Function interface. Used to create 15-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function15[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15): R
      |}
      |
      |/**
      | * A Function interface. Used to create 16-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function16[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16): R
      |}
      |
      |/**
      | * A Function interface. Used to create 17-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function17[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17): R
      |}
      |
      |/**
      | * A Function interface. Used to create 18-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function18[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18): R
      |}
      |
      |/**
      | * A Function interface. Used to create 19-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function19[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19): R
      |}
      |
      |/**
      | * A Function interface. Used to create 20-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function20[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20): R
      |}
      |
      |/**
      | * A Function interface. Used to create 21-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function21[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20, -T21, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20, arg21: T21): R
      |}
      |
      |/**
      | * A Function interface. Used to create 22-arg first-class-functions is Java.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Function22[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20, -T21, -T22, +R] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20, arg21: T21, arg22: T22): R
      |}
      |
      |/**
      | * A Consumer interface. Used to create 2-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure2[-T1, -T2] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 3-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure3[-T1, -T2, -T3] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 4-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure4[-T1, -T2, -T3, -T4] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 5-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure5[-T1, -T2, -T3, -T4, -T5] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 6-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure6[-T1, -T2, -T3, -T4, -T5, -T6] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 7-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure7[-T1, -T2, -T3, -T4, -T5, -T6, -T7] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 8-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure8[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 9-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure9[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 10-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure10[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 11-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure11[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 12-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure12[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 13-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure13[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 14-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure14[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 15-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure15[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 16-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure16[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 17-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure17[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 18-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure18[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 19-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure19[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 20-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure20[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 21-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure21[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20, -T21] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20, arg21: T21): Unit
      |}
      |
      |/**
      | * A Consumer interface. Used to create 22-arg consumers in Java.
      | * A Procedure is like a Function, but it doesn't produce a return value.
      | * `Serializable` is needed to be able to grab line number for Java 8 lambdas.
      | */
      |@nowarn("msg=@SerialVersionUID (has no effect|does nothing)")
      |@SerialVersionUID(1L)
      |@FunctionalInterface
      |trait Procedure22[-T1, -T2, -T3, -T4, -T5, -T6, -T7, -T8, -T9, -T10, -T11, -T12, -T13, -T14, -T15, -T16, -T17, -T18, -T19, -T20, -T21, -T22] extends java.io.Serializable {
      |  @throws(classOf[Exception])
      |  def apply(arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5, arg6: T6, arg7: T7, arg8: T8, arg9: T9, arg10: T10, arg11: T11, arg12: T12, arg13: T13, arg14: T14, arg15: T15, arg16: T16, arg17: T17, arg18: T18, arg19: T19, arg20: T20, arg21: T21, arg22: T22): Unit
      |}
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|org/apache/pekko/japi/tuple/Tuples.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// auto-generated by sbt-boilerplate
      |/*
      | * Licensed to the Apache Software Foundation (ASF) under one or more
      | * license agreements; and to You under the Apache License, version 2.0:
      | *
      | *   https://www.apache.org/licenses/LICENSE-2.0
      | *
      | * This file is part of the Apache Pekko project, which was derived from Akka.
      | */
      |
      |/*
      | * Copyright (C) 2015-2022 Lightbend Inc. <https://www.lightbend.com>
      | */
      |
      |package org.apache.pekko.japi.tuple
      |
      |/**
      | * Used to create tuples with 3 elements in Java.
      | */
      |object Tuple3 {
      |  def create[T1, T2, T3](t1: T1, t2: T2, t3: T3) = new Tuple3(t1, t2, t3)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple3[T1, T2, T3](t1: T1, t2: T2, t3: T3) {
      |   val toScala: (T1, T2, T3) = (t1, t2, t3)
      |}
      |
      |/**
      | * Used to create tuples with 4 elements in Java.
      | */
      |object Tuple4 {
      |  def create[T1, T2, T3, T4](t1: T1, t2: T2, t3: T3, t4: T4) = new Tuple4(t1, t2, t3, t4)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple4[T1, T2, T3, T4](t1: T1, t2: T2, t3: T3, t4: T4) {
      |   val toScala: (T1, T2, T3, T4) = (t1, t2, t3, t4)
      |}
      |
      |/**
      | * Used to create tuples with 5 elements in Java.
      | */
      |object Tuple5 {
      |  def create[T1, T2, T3, T4, T5](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5) = new Tuple5(t1, t2, t3, t4, t5)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple5[T1, T2, T3, T4, T5](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5) {
      |   val toScala: (T1, T2, T3, T4, T5) = (t1, t2, t3, t4, t5)
      |}
      |
      |/**
      | * Used to create tuples with 6 elements in Java.
      | */
      |object Tuple6 {
      |  def create[T1, T2, T3, T4, T5, T6](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6) = new Tuple6(t1, t2, t3, t4, t5, t6)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple6[T1, T2, T3, T4, T5, T6](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6) {
      |   val toScala: (T1, T2, T3, T4, T5, T6) = (t1, t2, t3, t4, t5, t6)
      |}
      |
      |/**
      | * Used to create tuples with 7 elements in Java.
      | */
      |object Tuple7 {
      |  def create[T1, T2, T3, T4, T5, T6, T7](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7) = new Tuple7(t1, t2, t3, t4, t5, t6, t7)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple7[T1, T2, T3, T4, T5, T6, T7](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7) = (t1, t2, t3, t4, t5, t6, t7)
      |}
      |
      |/**
      | * Used to create tuples with 8 elements in Java.
      | */
      |object Tuple8 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8) = new Tuple8(t1, t2, t3, t4, t5, t6, t7, t8)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple8[T1, T2, T3, T4, T5, T6, T7, T8](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8) = (t1, t2, t3, t4, t5, t6, t7, t8)
      |}
      |
      |/**
      | * Used to create tuples with 9 elements in Java.
      | */
      |object Tuple9 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9) = new Tuple9(t1, t2, t3, t4, t5, t6, t7, t8, t9)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9) = (t1, t2, t3, t4, t5, t6, t7, t8, t9)
      |}
      |
      |/**
      | * Used to create tuples with 10 elements in Java.
      | */
      |object Tuple10 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10) = new Tuple10(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
      |}
      |
      |/**
      | * Used to create tuples with 11 elements in Java.
      | */
      |object Tuple11 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11) = new Tuple11(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11)
      |}
      |
      |/**
      | * Used to create tuples with 12 elements in Java.
      | */
      |object Tuple12 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12) = new Tuple12(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12)
      |}
      |
      |/**
      | * Used to create tuples with 13 elements in Java.
      | */
      |object Tuple13 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13) = new Tuple13(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13)
      |}
      |
      |/**
      | * Used to create tuples with 14 elements in Java.
      | */
      |object Tuple14 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14) = new Tuple14(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14)
      |}
      |
      |/**
      | * Used to create tuples with 15 elements in Java.
      | */
      |object Tuple15 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15) = new Tuple15(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15)
      |}
      |
      |/**
      | * Used to create tuples with 16 elements in Java.
      | */
      |object Tuple16 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16) = new Tuple16(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16)
      |}
      |
      |/**
      | * Used to create tuples with 17 elements in Java.
      | */
      |object Tuple17 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17) = new Tuple17(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17)
      |}
      |
      |/**
      | * Used to create tuples with 18 elements in Java.
      | */
      |object Tuple18 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18) = new Tuple18(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18)
      |}
      |
      |/**
      | * Used to create tuples with 19 elements in Java.
      | */
      |object Tuple19 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19) = new Tuple19(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19)
      |}
      |
      |/**
      | * Used to create tuples with 20 elements in Java.
      | */
      |object Tuple20 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20) = new Tuple20(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20)
      |}
      |
      |/**
      | * Used to create tuples with 21 elements in Java.
      | */
      |object Tuple21 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21) = new Tuple21(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21)
      |}
      |
      |/**
      | * Used to create tuples with 22 elements in Java.
      | */
      |object Tuple22 {
      |  def create[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21, t22: T22) = new Tuple22(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22)
      |}
      |
      |/**
      | * Java API Tuple container.
      | */
      |@SerialVersionUID(1L)
      |final case class Tuple22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21, t22: T22) {
      |   val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22)
      |}
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.resources.resolve(s"""|META-INF/LICENSE""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|                                 Apache License
      |                           Version 2.0, January 2004
      |                        http://www.apache.org/licenses/
      |
      |   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
      |
      |   1. Definitions.
      |
      |      "License" shall mean the terms and conditions for use, reproduction,
      |      and distribution as defined by Sections 1 through 9 of this document.
      |
      |      "Licensor" shall mean the copyright owner or entity authorized by
      |      the copyright owner that is granting the License.
      |
      |      "Legal Entity" shall mean the union of the acting entity and all
      |      other entities that control, are controlled by, or are under common
      |      control with that entity. For the purposes of this definition,
      |      "control" means (i) the power, direct or indirect, to cause the
      |      direction or management of such entity, whether by contract or
      |      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      |      outstanding shares, or (iii) beneficial ownership of such entity.
      |
      |      "You" (or "Your") shall mean an individual or Legal Entity
      |      exercising permissions granted by this License.
      |
      |      "Source" form shall mean the preferred form for making modifications,
      |      including but not limited to software source code, documentation
      |      source, and configuration files.
      |
      |      "Object" form shall mean any form resulting from mechanical
      |      transformation or translation of a Source form, including but
      |      not limited to compiled object code, generated documentation,
      |      and conversions to other media types.
      |
      |      "Work" shall mean the work of authorship, whether in Source or
      |      Object form, made available under the License, as indicated by a
      |      copyright notice that is included in or attached to the work
      |      (an example is provided in the Appendix below).
      |
      |      "Derivative Works" shall mean any work, whether in Source or Object
      |      form, that is based on (or derived from) the Work and for which the
      |      editorial revisions, annotations, elaborations, or other modifications
      |      represent, as a whole, an original work of authorship. For the purposes
      |      of this License, Derivative Works shall not include works that remain
      |      separable from, or merely link (or bind by name) to the interfaces of,
      |      the Work and Derivative Works thereof.
      |
      |      "Contribution" shall mean any work of authorship, including
      |      the original version of the Work and any modifications or additions
      |      to that Work or Derivative Works thereof, that is intentionally
      |      submitted to Licensor for inclusion in the Work by the copyright owner
      |      or by an individual or Legal Entity authorized to submit on behalf of
      |      the copyright owner. For the purposes of this definition, "submitted"
      |      means any form of electronic, verbal, or written communication sent
      |      to the Licensor or its representatives, including but not limited to
      |      communication on electronic mailing lists, source code control systems,
      |      and issue tracking systems that are managed by, or on behalf of, the
      |      Licensor for the purpose of discussing and improving the Work, but
      |      excluding communication that is conspicuously marked or otherwise
      |      designated in writing by the copyright owner as "Not a Contribution."
      |
      |      "Contributor" shall mean Licensor and any individual or Legal Entity
      |      on behalf of whom a Contribution has been received by Licensor and
      |      subsequently incorporated within the Work.
      |
      |   2. Grant of Copyright License. Subject to the terms and conditions of
      |      this License, each Contributor hereby grants to You a perpetual,
      |      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      |      copyright license to reproduce, prepare Derivative Works of,
      |      publicly display, publicly perform, sublicense, and distribute the
      |      Work and such Derivative Works in Source or Object form.
      |
      |   3. Grant of Patent License. Subject to the terms and conditions of
      |      this License, each Contributor hereby grants to You a perpetual,
      |      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      |      (except as stated in this section) patent license to make, have made,
      |      use, offer to sell, sell, import, and otherwise transfer the Work,
      |      where such license applies only to those patent claims licensable
      |      by such Contributor that are necessarily infringed by their
      |      Contribution(s) alone or by combination of their Contribution(s)
      |      with the Work to which such Contribution(s) was submitted. If You
      |      institute patent litigation against any entity (including a
      |      cross-claim or counterclaim in a lawsuit) alleging that the Work
      |      or a Contribution incorporated within the Work constitutes direct
      |      or contributory patent infringement, then any patent licenses
      |      granted to You under this License for that Work shall terminate
      |      as of the date such litigation is filed.
      |
      |   4. Redistribution. You may reproduce and distribute copies of the
      |      Work or Derivative Works thereof in any medium, with or without
      |      modifications, and in Source or Object form, provided that You
      |      meet the following conditions:
      |
      |      (a) You must give any other recipients of the Work or
      |          Derivative Works a copy of this License; and
      |
      |      (b) You must cause any modified files to carry prominent notices
      |          stating that You changed the files; and
      |
      |      (c) You must retain, in the Source form of any Derivative Works
      |          that You distribute, all copyright, patent, trademark, and
      |          attribution notices from the Source form of the Work,
      |          excluding those notices that do not pertain to any part of
      |          the Derivative Works; and
      |
      |      (d) If the Work includes a "NOTICE" text file as part of its
      |          distribution, then any Derivative Works that You distribute must
      |          include a readable copy of the attribution notices contained
      |          within such NOTICE file, excluding those notices that do not
      |          pertain to any part of the Derivative Works, in at least one
      |          of the following places: within a NOTICE text file distributed
      |          as part of the Derivative Works; within the Source form or
      |          documentation, if provided along with the Derivative Works; or,
      |          within a display generated by the Derivative Works, if and
      |          wherever such third-party notices normally appear. The contents
      |          of the NOTICE file are for informational purposes only and
      |          do not modify the License. You may add Your own attribution
      |          notices within Derivative Works that You distribute, alongside
      |          or as an addendum to the NOTICE text from the Work, provided
      |          that such additional attribution notices cannot be construed
      |          as modifying the License.
      |
      |      You may add Your own copyright statement to Your modifications and
      |      may provide additional or different license terms and conditions
      |      for use, reproduction, or distribution of Your modifications, or
      |      for any such Derivative Works as a whole, provided Your use,
      |      reproduction, and distribution of the Work otherwise complies with
      |      the conditions stated in this License.
      |
      |   5. Submission of Contributions. Unless You explicitly state otherwise,
      |      any Contribution intentionally submitted for inclusion in the Work
      |      by You to the Licensor shall be under the terms and conditions of
      |      this License, without any additional terms or conditions.
      |      Notwithstanding the above, nothing herein shall supersede or modify
      |      the terms of any separate license agreement you may have executed
      |      with Licensor regarding such Contributions.
      |
      |   6. Trademarks. This License does not grant permission to use the trade
      |      names, trademarks, service marks, or product names of the Licensor,
      |      except as required for reasonable and customary use in describing the
      |      origin of the Work and reproducing the content of the NOTICE file.
      |
      |   7. Disclaimer of Warranty. Unless required by applicable law or
      |      agreed to in writing, Licensor provides the Work (and each
      |      Contributor provides its Contributions) on an "AS IS" BASIS,
      |      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      |      implied, including, without limitation, any warranties or conditions
      |      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      |      PARTICULAR PURPOSE. You are solely responsible for determining the
      |      appropriateness of using or redistributing the Work and assume any
      |      risks associated with Your exercise of permissions under this License.
      |
      |   8. Limitation of Liability. In no event and under no legal theory,
      |      whether in tort (including negligence), contract, or otherwise,
      |      unless required by applicable law (such as deliberate and grossly
      |      negligent acts) or agreed to in writing, shall any Contributor be
      |      liable to You for damages, including any direct, indirect, special,
      |      incidental, or consequential damages of any character arising as a
      |      result of this License or out of the use or inability to use the
      |      Work (including but not limited to damages for loss of goodwill,
      |      work stoppage, computer failure or malfunction, or any and all
      |      other commercial damages or losses), even if such Contributor
      |      has been advised of the possibility of such damages.
      |
      |   9. Accepting Warranty or Additional Liability. While redistributing
      |      the Work or Derivative Works thereof, You may choose to offer,
      |      and charge a fee for, acceptance of support, warranty, indemnity,
      |      or other liability obligations and/or rights consistent with this
      |      License. However, in accepting such obligations, You may act only
      |      on Your own behalf and on Your sole responsibility, not on behalf
      |      of any other Contributor, and only if You agree to indemnify,
      |      defend, and hold each Contributor harmless for any liability
      |      incurred by, or claims asserted against, such Contributor by reason
      |      of your accepting any such warranty or additional liability.
      |
      |   END OF TERMS AND CONDITIONS
      |
      |   APPENDIX: How to apply the Apache License to your work.
      |
      |      To apply the Apache License to your work, attach the following
      |      boilerplate notice, with the fields enclosed by brackets "[]"
      |      replaced with your own identifying information. (Don't include
      |      the brackets!)  The text should be enclosed in the appropriate
      |      comment syntax for the file format. We also recommend that a
      |      file or class name and description of purpose be included on the
      |      same "printed page" as the copyright notice for easier
      |      identification within third-party archives.
      |
      |   Copyright [yyyy] [name of copyright owner]
      |
      |   Licensed under the Apache License, Version 2.0 (the "License");
      |   you may not use this file except in compliance with the License.
      |   You may obtain a copy of the License at
      |
      |       http://www.apache.org/licenses/LICENSE-2.0
      |
      |   Unless required by applicable law or agreed to in writing, software
      |   distributed under the License is distributed on an "AS IS" BASIS,
      |   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      |   See the License for the specific language governing permissions and
      |   limitations under the License.
      |
      |---------------
      |
      |pekko-actor contains MurmurHash.scala which is derived from MurmurHash3,
      |written by Austin Appleby. He has placed his code in the public domain.
      |The author has disclaimed copyright to that source code.
      |MurmurHash.scala also contains changes made by the Scala-Lang team under an Apache 2.0 license.
      |Copyright (c) 2003-2011, LAMP/EPFL
      |
      |---------------
      |
      |pekko-actor contains code from scala-library which was released under an Apache 2.0 license.
      |- actor/src/main/scala/org/apache/pekko/util/Helpers.scala
      |
      |Scala (https://www.scala-lang.org)
      |
      |Copyright EPFL and Lightbend, Inc.
      |
      |---------------
      |
      |pekko-actor contains code from Netty which was released under an Apache 2.0 license.
      |Copyright 2014 The Netty Project
      |- actor/src/main/scala/org/apache/pekko/io/dns/DnsSettings.scala
      |- actor/src/main/scala/org/apache/pekko/util/SWARUtil.scala
      |
      |---------------
      |
      |pekko-actor contains code from java-uuid-generator <https://github.com/cowtowncoder/java-uuid-generator>
      |in `org.apache.pekko.util.UUIDComparator.scala` which was released under an Apache 2.0 license.
      |
      |---------------
      |
      |pekko-actor contains code in `org.apache.pekko.dispatch.AbstractNodeQueue.java` and in
      |`org.apache.pekko.dispatch.AbstractBoundedNodeQueue.java` which was based on
      |code from https://www.1024cores.net/home/lock-free-algorithms/queues/non-intrusive-mpsc-node-based-queue which
      |was released under the Simplified BSD license.
      |
      |Copyright (c) 2010-2011 Dmitry Vyukov. All rights reserved.
      |
      |Redistribution and use in source and binary forms, with or without modification, are permitted provided that
      |the following conditions are met:
      |
      |   1. Redistributions of source code must retain the above copyright notice, this list of
      |
      |      conditions and the following disclaimer.
      |
      |   2. Redistributions in binary form must reproduce the above copyright notice, this list
      |
      |      of conditions and the following disclaimer in the documentation and/or other materials
      |
      |      provided with the distribution.
      |
      |THIS SOFTWARE IS PROVIDED BY DMITRY VYUKOV "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
      |LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
      |IN NO EVENT SHALL DMITRY VYUKOV OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
      |EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
      |SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
      |LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
      |WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
      |
      |The views and conclusions contained in the software and documentation are those of the authors and should not
      |be interpreted as representing official policies, either expressed or implied, of Dmitry Vyukov.
      |
      |---------------
      |
      |pekko-actor contains code in `org.apache.pekko.dispatch.AbstractBoundedNodeQueue.java` which was based on
      |code from actors <https://github.com/plokhotnyuk/actors> which was released under the Apache 2.0 license.
      |
      |---------------
      |
      |pekko-actor contains code in `org.apache.pekko.util.FrequencySketch.scala` which was based on
      |code from hash-prospector <https://github.com/skeeto/hash-prospector> which has been placed
      |in the public domain.
      |
      |This is free and unencumbered software released into the public domain.
      |
      |Anyone is free to copy, modify, publish, use, compile, sell, or
      |distribute this software, either in source code form or as a compiled
      |binary, for any purpose, commercial or non-commercial, and by any
      |means.
      |
      |In jurisdictions that recognize copyright laws, the author or authors
      |of this software dedicate any and all copyright interest in the
      |software to the public domain. We make this dedication for the benefit
      |of the public at large and to the detriment of our heirs and
      |successors. We intend this dedication to be an overt act of
      |relinquishment in perpetuity of all present and future rights to this
      |software under copyright law.
      |
      |THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      |EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
      |MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
      |IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
      |OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
      |ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
      |OTHER DEALINGS IN THE SOFTWARE.
      |
      |For more information, please refer to <http://unlicense.org/>
      |
      |---------------
      |
      |pekko-actor contains code in `org.apache.pekko.util.FrequencySketch.scala` which was based on code from
      |Caffeine <https://github.com/ben-manes/caffeine> which was developed under the Apache 2.0 license.
      |Copyright 2015 Ben Manes. All Rights Reserved.
      |
      |---------------
      |
      |pekko-actor contains code from Apache commons-io which was developed under the
      |Apache 2.0 license.
      |- actor/src/main/java/org/apache/pekko/io/ByteBufferCleaner.java
      |- actor/src/main/java/org/apache/pekko/io/UnsynchronizedByteArrayInputStream.java
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.resources.resolve(s"""|META-INF/NOTICE""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|Apache Pekko
      |Copyright 2022-2026 The Apache Software Foundation
      |
      |This product includes software developed at
      |The Apache Software Foundation (https://www.apache.org/).
      |
      |This product contains significant parts that were originally based on software from Lightbend (Akka <https://akka.io/>).
      |Copyright (C) 2009-2022 Lightbend Inc. <https://www.lightbend.com>
      |
      |Apache Pekko is derived from Akka 2.6.x, the last version that was distributed under the
      |Apache License, Version 2.0 License.
      |
      |---------------
      |
      |pekko-actor contains MurmurHash.scala which has changes made by the Scala-Lang team under an Apache 2.0 license.
      |
      |Copyright (c) 2002-2023 EPFL
      |Copyright (c) 2011-2023 Lightbend, Inc.
      |
      |Scala includes software developed at
      |LAMP/EPFL (https://lamp.epfl.ch/) and
      |Lightbend, Inc. (https://www.lightbend.com/).
      |
      |---------------
      |
      |pekko-actor contains code from scala-library which was released under an Apache 2.0 license.
      |
      |Scala
      |Copyright (c) 2002-2023 EPFL
      |Copyright (c) 2011-2023 Lightbend, Inc.
      |
      |Scala includes software developed at
      |LAMP/EPFL (https://lamp.epfl.ch/) and
      |Lightbend, Inc. (https://www.lightbend.com/).
      |
      |---------------
      |
      |pekko-actor contains code from Netty which was released under an Apache 2.0 license.
      |
      |                            The Netty Project
      |                            =================
      |
      |Please visit the Netty web site for more information:
      |
      |  * https://netty.io/
      |
      |Copyright 2014 The Netty Project
      |
      |The Netty Project licenses this file to you under the Apache License,
      |version 2.0 (the "License"); you may not use this file except in compliance
      |with the License. You may obtain a copy of the License at:
      |
      |  https://www.apache.org/licenses/LICENSE-2.0
      |
      |---------------
      |
      |pekko-actor contains code from java-uuid-generator <https://github.com/cowtowncoder/java-uuid-generator>
      |in `org.apache.pekko.util.UUIDComparator.scala` which was released under an Apache 2.0 license.
      |
      |Java UUID generator library has been written by Tatu Saloranta (tatu.saloranta@iki.fi)
      |
      |Other developers who have contributed code are:
      |
      |* Eric Bie contributed extensive unit test suite which has helped ensure high implementation
      |  quality
      |
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }



    targets.foreach { target =>
      if (Set(s"""|pekko-actor@jvm213""".stripMargin, s"""|pekko-actor@jvm3""".stripMargin).contains(target.project.value)) {
        val to = target.resources.resolve(s"""|version.conf""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|pekko.version = "2.0.0-M4+81-c2bc0f1c-SNAPSHOT"
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}