
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForBloopBackend extends BleepCodegenScript("GenerateForBloopBackend") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set(s"""|bloop-backend""".stripMargin).contains(target.project.value)) {
        val to = target.sources.resolve(s"""|sbt-buildinfo/BloopScalaInfo.scala""".stripMargin)
        started.logger.withContext("project", target.project.value).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package bloop.internal.build
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BloopScalaInfo {
      |  /** The value is "2.12.20". */
      |  val scalaVersion: String = "2.12.20"
      |  /** The value is "org.scala-lang". */
      |  val scalaOrganization: String = "org.scala-lang"
      |  override val toString: String = {
      |    "scalaVersion: %s, scalaOrganization: %s".format(
      |      scalaVersion, scalaOrganization
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$
      |""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}