
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForBloopFrontend extends BleepCodegenScript("GenerateForBloopFrontend") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("bloop-frontend").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package bloop.internal.build
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "ch.epfl.scala". */
      |  val organization: String = "ch.epfl.scala"
      |  /** The value is "bloop". */
      |  val bloopName: String = "bloop"
      |  /** The value is "1.5.6-217-cc04a065-20230529-1250-SNAPSHOT". */
      |  val version: String = "1.5.6-217-cc04a065-20230529-1250-SNAPSHOT"
      |  /** The value is "2.12.17". */
      |  val scalaVersion: String = "2.12.17"
      |  /** The value is new java.io.File("<BLEEP_GIT>/snapshot-tests/bloop/sbt-build/nailgun/pynailgun/ng.py"). */
      |  val nailgunClientLocation: java.io.File = new java.io.File("<BLEEP_GIT>/snapshot-tests/bloop/sbt-build/nailgun/pynailgun/ng.py")
      |  /** The value is "1.8.1". */
      |  val zincVersion: String = "1.8.1"
      |  /** The value is "2.1.0-M3". */
      |  val bspVersion: String = "2.1.0-M3"
      |  /** The value is "bloop-native-bridge-0-4_2.12". */
      |  val nativeBridge04: String = "bloop-native-bridge-0-4_2.12"
      |  /** The value is "bloop-js-bridge-0-6_2.12". */
      |  val jsBridge06: String = "bloop-js-bridge-0-6_2.12"
      |  /** The value is "bloop-js-bridge-1_2.12". */
      |  val jsBridge1: String = "bloop-js-bridge-1_2.12"
      |  override val toString: String = {
      |    "organization: %s, bloopName: %s, version: %s, scalaVersion: %s, nailgunClientLocation: %s, zincVersion: %s, bspVersion: %s, nativeBridge04: %s, jsBridge06: %s, jsBridge1: %s".format(
      |      organization, bloopName, version, scalaVersion, nailgunClientLocation, zincVersion, bspVersion, nativeBridge04, jsBridge06, jsBridge1
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}