
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForMavenBloop extends BleepCodegenScript("GenerateForMavenBloop") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("maven-bloop").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|package bloop
      |
      |import scala.Predef._
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "1.5.2-9-b190bd39-20221105-0119". */
      |  val version: String = "1.5.2-9-b190bd39-20221105-0119"
      |  override val toString: String = {
      |    "version: %s" format (
      |      version
      |    )
      |  }
      |}""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}