
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForBloopFrontend extends BleepCodegenScript("GenerateForBloopFrontend") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("bloop-frontend").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|package bloop.internal.build
      |
      |import scala.Predef._
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "ch.epfl.scala". */
      |  val organization: String = "ch.epfl.scala"
      |  /** The value is "bloop". */
      |  val bloopName: String = "bloop"
      |  /** The value is "1.5.2-9-b190bd39-20221105-0119". */
      |  val version: String = "1.5.2-9-b190bd39-20221105-0119"
      |  /** The value is "2.12.15". */
      |  val scalaVersion: String = "2.12.15"
      |  /** The value is "1.6.2". */
      |  val sbtVersion: String = "1.6.2"
      |  /** The value is new java.io.File("<BLEEP_GIT>/snapshot-tests/bloop/sbt-build/nailgun/pynailgun/ng.py"). */
      |  val nailgunClientLocation: java.io.File = new java.io.File("<BLEEP_GIT>/snapshot-tests/bloop/sbt-build/nailgun/pynailgun/ng.py")
      |  /** The value is "1.6.0". */
      |  val zincVersion: String = "1.6.0"
      |  /** The value is scala.collection.Seq("Jorge Vicente Cantero", "Martin Duhem"). */
      |  val developers = scala.collection.Seq("Jorge Vicente Cantero", "Martin Duhem")
      |  /** The value is "bloop-native-bridge-0-4_2.12". */
      |  val nativeBridge04: String = "bloop-native-bridge-0-4_2.12"
      |  /** The value is "bloop-js-bridge-0-6_2.12". */
      |  val jsBridge06: String = "bloop-js-bridge-0-6_2.12"
      |  /** The value is "bloop-js-bridge-1_2.12". */
      |  val jsBridge1: String = "bloop-js-bridge-1_2.12"
      |  /** The value is "2.0.0-M13". */
      |  val bspVersion: String = "2.0.0-M13"
      |  override val toString: String = {
      |    "organization: %s, bloopName: %s, version: %s, scalaVersion: %s, sbtVersion: %s, nailgunClientLocation: %s, zincVersion: %s, developers: %s, nativeBridge04: %s, jsBridge06: %s, jsBridge1: %s, bspVersion: %s" format (
      |      organization, bloopName, version, scalaVersion, sbtVersion, nailgunClientLocation, zincVersion, developers, nativeBridge04, jsBridge06, jsBridge1, bspVersion
      |    )
      |  }
      |}""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}