
package scripts

import bleep.{BleepCodegenScript, Commands, Started}

import java.nio.file.Files

object GenerateForBloopCli extends BleepCodegenScript("GenerateForBloopCli") {
  override def run(started: Started, commands: Commands, targets: List[Target], args: List[String]): Unit = {
    started.logger.error("This script is a placeholder! You'll need to replace the contents with code which actually generates the files you want")

    targets.foreach { target =>
      if (Set("bloop-cli").contains(target.project.value)) {
        val to = target.sources.resolve("sbt-buildinfo/BuildInfo.scala")
        started.logger.withContext(target.project).warn(s"Writing $to")
        val content = s"""|// $$COVERAGE-OFF$$
      |package buildinfo
      |
      |/** This object was generated by sbt-buildinfo. */
      |case object BuildInfo {
      |  /** The value is "bloop-cli". */
      |  val name: String = "bloop-cli"
      |  /** The value is "2.0.10-0-051ce0a1-20250622-0035-SNAPSHOT". */
      |  val version: String = "2.0.10-0-051ce0a1-20250622-0035-SNAPSHOT"
      |  /** The value is "2.13.16". */
      |  val scalaVersion: String = "2.13.16"
      |  /** The value is "1.10.11". */
      |  val sbtVersion: String = "1.10.11"
      |  override val toString: String = {
      |    "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s".format(
      |      name, version, scalaVersion, sbtVersion
      |    )
      |  }
      |}
      |// $$COVERAGE-ON$$""".stripMargin
        Files.createDirectories(to.getParent)
        Files.writeString(to, content)
      }
    }

  }
}