// $COVERAGE-OFF$
package org.http4s

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "1.0-f4419aa-SNAPSHOT". */
  val version: String = "1.0-f4419aa-SNAPSHOT"
  /** The value is "3.3.6". */
  val scalaVersion: String = "3.3.6"
  /** The value is (1 -> 0). */
  val apiVersion = (1 -> 0)
  override val toString: String = {
    "version: %s, scalaVersion: %s, apiVersion: %s".format(
      version, scalaVersion, apiVersion
    )
  }
}
// $COVERAGE-ON$
